---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: debian-10

suites:
  - name: default
    run_list:
      - recipe[codenamephp_dev::chrome]
      - recipe[codenamephp_dev::dnsmasq]
      - recipe[codenamephp_dev::vscode]
      - recipe[codenamephp_dev::gnome_terminal]
      - recipe[codenamephp_dev::unzip]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
