---
driver:
  name: vagrant
provisioner:
  name: chef_solo
verifier:
  name: inspec
platforms:
  - name: debian-9.1

suites:
  - name: default
    run_list:
      - recipe[chef.cookbook.dev::chrome]
      - recipe[chef.cookbook.dev::openjdk8]
    attributes:
    verifier:
      inspec_tests:
        - test/smoke/default