driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: current
  intermediate_instructions:
    - RUN apt-get install sudo
    
transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true
 
platforms:
  - name: debian-9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd
