AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'bundler/**'

Layout/EndOfLine:
  EnforcedStyle: lf
  
Layout/LineLength:
  Max: 200 

Metrics/BlockLength:
  Max: 200
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'test/smoke/**/*.rb'
    
Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 25

Metrics/ParameterLists:
  Max: 10

Metrics/ModuleLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'test/smoke/**/*.rb'
  
Lint/AmbiguousBlockAssociation:
  Enabled: false
