AllCops:
  Exclude:
    - 'bin/**'
    - 'bundler/**'

Layout/EndOfLine:
  EnforcedStyle: lf
  
Metrics/LineLength:
  Max: 200

Metrics/BlockLength:
  Max: 200
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'test/smoke/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'test/smoke/**/*.rb'
  
Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/MethodLength:
  Max: 50